
package frc.robot.choreo;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If these imports cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj GreedyFirstDip = new ChoreoTraj(
	    "GreedyFirstDip",
	    OptionalInt.empty(),
	    4.83569,
	    new Pose2d(4.327, 7.391, Rotation2d.fromRadians(-1.514)),
	    new Pose2d(3.002, 7.076, Rotation2d.fromRadians(-1.047))
	);
	public static final ChoreoTraj MV1 = new ChoreoTraj(
	    "MV1",
	    OptionalInt.empty(),
	    2.36221,
	    new Pose2d(4.324, 7.35, Rotation2d.fromRadians(0)),
	    new Pose2d(7.372, 4.477, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj seconddip = new ChoreoTraj(
	    "seconddip",
	    OptionalInt.empty(),
	    6.97386,
	    new Pose2d(3.08, 7.417, Rotation2d.fromRadians(0)),
	    new Pose2d(2.752, 6.499, Rotation2d.fromRadians(-0.94))
	);
	public static final ChoreoTraj test = new ChoreoTraj(
	    "test",
	    OptionalInt.empty(),
	    3.24871,
	    new Pose2d(6.607, 6.988, Rotation2d.fromRadians(0)),
	    new Pose2d(6.597, 7.009, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj Trench1 = new ChoreoTraj(
	    "Trench1",
	    OptionalInt.empty(),
	    9.39149,
	    new Pose2d(3.972, 7.472, Rotation2d.fromRadians(-1.386)),
	    new Pose2d(3.064, 6.894, Rotation2d.fromRadians(-1.078))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("GreedyFirstDip", GreedyFirstDip),
		Map.entry("MV1", MV1),
		Map.entry("seconddip", seconddip),
		Map.entry("test", test),
		Map.entry("Trench1", Trench1)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
