
package frc.robot.choreo;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If these imports cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj AllNeutralRun = new ChoreoTraj(
	    "AllNeutralRun",
	    OptionalInt.empty(),
	    9.00027,
	    new Pose2d(3.327, 7.393, Rotation2d.fromRadians(0)),
	    new Pose2d(7.796, 5.675, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj AllNeutralRun$0 = new ChoreoTraj(
	    "AllNeutralRun",
	    OptionalInt.of(0),
	    6.48638,
	    new Pose2d(3.327, 7.393, Rotation2d.fromRadians(0)),
	    new Pose2d(2.594, 7.34, Rotation2d.fromRadians(-1.025))
	);
	public static final ChoreoTraj AllNeutralRun$1 = new ChoreoTraj(
	    "AllNeutralRun",
	    OptionalInt.of(1),
	    2.513890000000001,
	    new Pose2d(2.594, 7.34, Rotation2d.fromRadians(-1.025)),
	    new Pose2d(7.796, 5.675, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj funnyintaketrench = new ChoreoTraj(
	    "funnyintaketrench",
	    OptionalInt.empty(),
	    8.5824,
	    new Pose2d(4.327, 7.521, Rotation2d.fromRadians(0)),
	    new Pose2d(2.916, 6.69, Rotation2d.fromRadians(-1.055))
	);
	public static final ChoreoTraj funnyintaketrench$0 = new ChoreoTraj(
	    "funnyintaketrench",
	    OptionalInt.of(0),
	    1.52754,
	    new Pose2d(4.327, 7.521, Rotation2d.fromRadians(0)),
	    new Pose2d(8.572, 6.991, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj funnyintaketrench$1 = new ChoreoTraj(
	    "funnyintaketrench",
	    OptionalInt.of(1),
	    7.05486,
	    new Pose2d(8.572, 6.991, Rotation2d.fromRadians(0)),
	    new Pose2d(2.916, 6.69, Rotation2d.fromRadians(-1.055))
	);
	public static final ChoreoTraj greedydoubledip = new ChoreoTraj(
	    "greedydoubledip",
	    OptionalInt.empty(),
	    11.99464,
	    new Pose2d(4.327, 7.391, Rotation2d.fromRadians(0)),
	    new Pose2d(3.097, 6.916, Rotation2d.fromRadians(-1.086))
	);
	public static final ChoreoTraj greedydoubledip$0 = new ChoreoTraj(
	    "greedydoubledip",
	    OptionalInt.of(0),
	    4.87993,
	    new Pose2d(4.327, 7.391, Rotation2d.fromRadians(0)),
	    new Pose2d(3.002, 7.076, Rotation2d.fromRadians(-1.047))
	);
	public static final ChoreoTraj greedydoubledip$1 = new ChoreoTraj(
	    "greedydoubledip",
	    OptionalInt.of(1),
	    7.1147100000000005,
	    new Pose2d(3.002, 7.076, Rotation2d.fromRadians(-1.047)),
	    new Pose2d(3.097, 6.916, Rotation2d.fromRadians(-1.086))
	);
	public static final ChoreoTraj greedyfunnybump = new ChoreoTraj(
	    "greedyfunnybump",
	    OptionalInt.empty(),
	    7.27189,
	    new Pose2d(4.327, 7.391, Rotation2d.fromRadians(-1.514)),
	    new Pose2d(2.835, 7.151, Rotation2d.fromRadians(-1.049))
	);
	public static final ChoreoTraj greedyfunnybump$0 = new ChoreoTraj(
	    "greedyfunnybump",
	    OptionalInt.of(0),
	    5.29586,
	    new Pose2d(4.327, 7.391, Rotation2d.fromRadians(-1.514)),
	    new Pose2d(1.734, 5.909, Rotation2d.fromRadians(-0.568))
	);
	public static final ChoreoTraj greedyfunnybump$1 = new ChoreoTraj(
	    "greedyfunnybump",
	    OptionalInt.of(1),
	    1.9760299999999997,
	    new Pose2d(1.734, 5.909, Rotation2d.fromRadians(-0.568)),
	    new Pose2d(2.835, 7.151, Rotation2d.fromRadians(-1.049))
	);
	public static final ChoreoTraj greedyfunnytench = new ChoreoTraj(
	    "greedyfunnytench",
	    OptionalInt.empty(),
	    6.22739,
	    new Pose2d(4.327, 7.391, Rotation2d.fromRadians(-1.514)),
	    new Pose2d(3.002, 7.076, Rotation2d.fromRadians(-1.047))
	);
	public static final ChoreoTraj Mid = new ChoreoTraj(
	    "Mid",
	    OptionalInt.empty(),
	    1.70894,
	    new Pose2d(3.606, 3.985, Rotation2d.fromRadians(3.131)),
	    new Pose2d(2.027, 3.999, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj optimizedtoptrench = new ChoreoTraj(
	    "optimizedtoptrench",
	    OptionalInt.empty(),
	    11.82963,
	    new Pose2d(4.327, 7.393, Rotation2d.fromRadians(0)),
	    new Pose2d(2.816, 6.888, Rotation2d.fromRadians(-1.019))
	);
	public static final ChoreoTraj OtherDoubleTrench = new ChoreoTraj(
	    "OtherDoubleTrench",
	    OptionalInt.empty(),
	    12.60529,
	    new Pose2d(4.313, 0.647, Rotation2d.fromRadians(0)),
	    new Pose2d(1.501, 1.603, Rotation2d.fromRadians(0.667))
	);
	public static final ChoreoTraj OtherDoubleTrench$0 = new ChoreoTraj(
	    "OtherDoubleTrench",
	    OptionalInt.of(0),
	    5.86766,
	    new Pose2d(4.313, 0.647, Rotation2d.fromRadians(0)),
	    new Pose2d(2.595, 1.409, Rotation2d.fromRadians(0.936))
	);
	public static final ChoreoTraj OtherDoubleTrench$1 = new ChoreoTraj(
	    "OtherDoubleTrench",
	    OptionalInt.of(1),
	    6.73763,
	    new Pose2d(2.595, 1.409, Rotation2d.fromRadians(0.936)),
	    new Pose2d(1.501, 1.603, Rotation2d.fromRadians(0.667))
	);
	public static final ChoreoTraj OtherSingleTrench = new ChoreoTraj(
	    "OtherSingleTrench",
	    OptionalInt.empty(),
	    5.94147,
	    new Pose2d(4.313, 0.647, Rotation2d.fromRadians(0)),
	    new Pose2d(2.595, 1.409, Rotation2d.fromRadians(0.667))
	);
	public static final ChoreoTraj realtoptrenchdouble = new ChoreoTraj(
	    "realtoptrenchdouble",
	    OptionalInt.empty(),
	    12.10566,
	    new Pose2d(4.327, 7.393, Rotation2d.fromRadians(0)),
	    new Pose2d(1.639, 7.019, Rotation2d.fromRadians(-0.785))
	);
	public static final ChoreoTraj realtoptrenchdouble$0 = new ChoreoTraj(
	    "realtoptrenchdouble",
	    OptionalInt.of(0),
	    5.64231,
	    new Pose2d(4.327, 7.393, Rotation2d.fromRadians(0)),
	    new Pose2d(2.676, 6.881, Rotation2d.fromRadians(-0.962))
	);
	public static final ChoreoTraj realtoptrenchdouble$1 = new ChoreoTraj(
	    "realtoptrenchdouble",
	    OptionalInt.of(1),
	    6.46335,
	    new Pose2d(2.676, 6.881, Rotation2d.fromRadians(-0.962)),
	    new Pose2d(1.639, 7.019, Rotation2d.fromRadians(-0.785))
	);
	public static final ChoreoTraj realtoptrenchsingle = new ChoreoTraj(
	    "realtoptrenchsingle",
	    OptionalInt.empty(),
	    5.54029,
	    new Pose2d(4.327, 7.393, Rotation2d.fromRadians(0)),
	    new Pose2d(2.594, 7.34, Rotation2d.fromRadians(-1.025))
	);
	public static final ChoreoTraj Trench1 = new ChoreoTraj(
	    "Trench1",
	    OptionalInt.empty(),
	    9.39149,
	    new Pose2d(3.972, 7.472, Rotation2d.fromRadians(-1.386)),
	    new Pose2d(3.064, 6.894, Rotation2d.fromRadians(-1.078))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("AllNeutralRun", AllNeutralRun),
		Map.entry("AllNeutralRun$0", AllNeutralRun$0),
		Map.entry("AllNeutralRun$1", AllNeutralRun$1),
		Map.entry("funnyintaketrench", funnyintaketrench),
		Map.entry("funnyintaketrench$0", funnyintaketrench$0),
		Map.entry("funnyintaketrench$1", funnyintaketrench$1),
		Map.entry("greedydoubledip", greedydoubledip),
		Map.entry("greedydoubledip$0", greedydoubledip$0),
		Map.entry("greedydoubledip$1", greedydoubledip$1),
		Map.entry("greedyfunnybump", greedyfunnybump),
		Map.entry("greedyfunnybump$0", greedyfunnybump$0),
		Map.entry("greedyfunnybump$1", greedyfunnybump$1),
		Map.entry("greedyfunnytench", greedyfunnytench),
		Map.entry("Mid", Mid),
		Map.entry("optimizedtoptrench", optimizedtoptrench),
		Map.entry("OtherDoubleTrench", OtherDoubleTrench),
		Map.entry("OtherDoubleTrench$0", OtherDoubleTrench$0),
		Map.entry("OtherDoubleTrench$1", OtherDoubleTrench$1),
		Map.entry("OtherSingleTrench", OtherSingleTrench),
		Map.entry("realtoptrenchdouble", realtoptrenchdouble),
		Map.entry("realtoptrenchdouble$0", realtoptrenchdouble$0),
		Map.entry("realtoptrenchdouble$1", realtoptrenchdouble$1),
		Map.entry("realtoptrenchsingle", realtoptrenchsingle),
		Map.entry("Trench1", Trench1)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
